# Generated by Django 5.2.8 on 2025-11-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hours', models.CharField(max_length=255)),
                ('student', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
            ],
        ),
    ]
